; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040 
framework = arduino
board_build.core = earlephilhower

lib_deps = 
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    https://github.com/adafruit/Adafruit_NeoPixel.git
    https://github.com/Bodmer/TJpg_Decoder.git

board_build.f_cpu = 133000000L
board_build.filesystem = 1m


