# config.yaml
# LT3751設計用入力パラメータ

# --- 電圧、電流 ---
# Vout:        300.0    # 目標出力電圧 [V]
VtransMax:   25.0   # トランス１次入力電圧 [V]
VtransMin:   20.0   # トランス１次入力電圧 [V]
# Vcc:         6.5      # LT3751 VCC 電圧 [V]
# Ipk:         9.0      # 目標ピーク一次電流[A] trans750032052依存(MAXが10A)

# --- デバイス関連 ---
# trans750032052
N:           10.0       #巻き数比 trans750032052依存
Lpri:        10.0e-6    #変圧器の一次側のインダクタンス[H] trans750032052依存
# diode
Vdiode:      1.0        #出力ダイオードの順方向電圧降下[V]
# resistor　データシート表2より
RVtrans:     40.2e+3    #RVtransの抵抗値[Ω]
RVout:       40.2e+3    #RVoutの抵抗値[Ω]
Rdcm:        18.2e+3    #Rdcmの抵抗値[Ω]
Rbg:         1.15e+3     #Rbgの抵抗値[Ω]
Rsense:      12.0e-3    #Rsenseの抵抗値[Ω]

# FBピンの電圧
Vfb:         280        #充電モードからレギュレーションモードに移行するFBピンの電圧[V]
Rfbl:        1.0e+3     #FBピンの下の抵抗値[Ω]